### PR TITLE
[WIP] GCE to GCP

### PR DESCRIPTION
**Pull request by almahmoud**
Not fully tested yet.
Goes with: https://github.com/galaxyproject/cloudlaunch/pull/167 https://github.com/galaxyproject/cloudlaunch-ui/pull/37 https://github.com/CloudVE/cloudbridge/commit/370487fc4e14be565d0e939f11b8d16b94e24571
https://github.com/CloudVE/cloudlaunch-cli/pull/14

### CODE REVIEW

**Comment by nuwang** [comment]
@almahmoud This looks like it needs a migration generated for it?

**Comment by almahmoud** [comment]
> @almahmoud This looks like it needs a migration generated for it, to handle existing tables?

Yes! I forgot to add it to the last commit, my bad!

**Comment by nuwang** [comment]
I've pushed in a patch to fix tests for cloudbridge 2.0.0: https://github.com/CloudVE/djcloudbridge/commit/9ecd36fa7b57ac63f0ce37babb08deb43420b044
Can you try merging that branch and see whether the tests pass? Also, is this ready to merge or does it need more testing?

**Comment by almahmoud** [comment]
> I've pushed in a patch to fix tests for cloudbridge 2.0.0: [9ecd36f](https://github.com/CloudVE/djcloudbridge/commit/9ecd36fa7b57ac63f0ce37babb08deb43420b044)
> Can you try merging that branch and see whether the tests pass? Also, is this ready to merge or does it need more testing?

Done! As for testing, when combining all the PR's with CB master branch, I was able to properly get an ubuntu instance going on GCP, so I believe that it works in regards to the GCP renaming aspect. We could merge now if that's all we're changing, but if we do the zone change in CB 2.0, maybe we should wait until we integrate those changes as well?

**Pull request merged**
